name: "HabitBridge"
description: "Process webhooks from HabitBridge habit tracking app"
version: "1.0.0"
slug: "habitbridge"
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
ports:
  8000/tcp: 8000
ports_description:
  8000/tcp: "Webhook endpoint"
options:
  log_level: info
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)